"""
Firewall Analysis — Visualization Suite
Stateful vs. Stateless Firewall Comparison Study
Advanced Network Security (A0347132)

GitHub: https://github.com/EvilGroundZero/Network-Security-Paper-Codes

Reads:   results/scan_results.csv
Outputs: charts/chart1_evasion_resistance.png
         charts/chart2_port_state_breakdown.png
         charts/chart3_latency_comparison.png
         charts/chart4_radar_posture.png

Usage:
    pip install pandas matplotlib numpy
    python3 firewall_plot.py
"""

import os
import sys
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

# ── Paths ─────────────────────────────────────────────────────────────────────
CSV_PATH    = os.path.join("results", "scan_results.csv")
CHARTS_DIR  = "charts"
os.makedirs(CHARTS_DIR, exist_ok=True)

# ── Load & validate ───────────────────────────────────────────────────────────
if not os.path.exists(CSV_PATH):
    print(f"[!] '{CSV_PATH}' not found. Run firewall_lab.sh first.")
    sys.exit(1)

df_all = pd.read_csv(CSV_PATH)

# Sanity check: if the CSV was generated by the old buggy script,
# the columns will be malformed. Detect and fix automatically.
expected_cols = {"Firewall", "Scan_Type", "Filtered_Ports",
                 "Closed_Ports", "Open_Ports", "Latency_ms"}
if not expected_cols.issubset(set(df_all.columns)):
    print("[!] Detected malformed CSV (old script bug — embedded newlines).")
    print("[*] Auto-fixing by re-parsing...")
    raw = open(CSV_PATH).read()
    from io import StringIO
    df_all = pd.read_csv(StringIO(raw.replace("\n0,", ",")))
    df_all = df_all.dropna()
    print("[+] Fix applied.")

# Separate flood row from main data
flood_mask  = df_all["Scan_Type"] == "SYN_Flood_Recovery"
df          = df_all[~flood_mask].copy().reset_index(drop=True)
df_flood    = df_all[flood_mask].copy()

sl = df[df["Firewall"] == "Stateless"].reset_index(drop=True)
sf = df[df["Firewall"] == "Stateful"].reset_index(drop=True)

if len(sl) == 0 or len(sf) == 0:
    print("[!] No data found for one or both firewall types. Check CSV.")
    sys.exit(1)

scans = sl["Scan_Type"].values
print(f"[+] Loaded {len(df)} scan records across {len(scans)} attack types.")
print(df.to_string(index=False))

# ── Theme ─────────────────────────────────────────────────────────────────────
BG      = "#0D1117"
SURFACE = "#161B22"
GRID    = "#21262D"
C_SL    = "#FF6B9D"   # stateless: neon pink
C_SF    = "#7C3AED"   # stateful:  deep purple
C_OPEN  = "#F97316"   # open ports (orange — danger)
C_FILT  = "#22C55E"   # filtered   (green  — safe)
C_CLOS  = "#64748B"   # closed     (slate)
WHITE   = "#F0F6FF"
MUTED   = "#8B949E"

plt.rcParams.update({
    "font.family":       "DejaVu Sans",
    "axes.spines.top":   False,
    "axes.spines.right": False,
})

def apply_dark(ax):
    ax.set_facecolor(SURFACE)
    ax.tick_params(colors=WHITE, labelsize=9)
    ax.yaxis.label.set_color(WHITE)
    ax.xaxis.label.set_color(WHITE)
    ax.title.set_color(WHITE)
    ax.spines["left"].set_color(GRID)
    ax.spines["bottom"].set_color(GRID)
    ax.yaxis.grid(True, linestyle="--", color=GRID, alpha=0.8, zorder=0)
    ax.set_axisbelow(True)

def autolabel(ax, rects, color=WHITE):
    for r in rects:
        h = r.get_height()
        if h > 0:
            ax.annotate(f"{int(h)}",
                        xy=(r.get_x() + r.get_width() / 2, h),
                        xytext=(0, 4), textcoords="offset points",
                        ha="center", va="bottom",
                        color=color, fontsize=8, fontweight="bold")

x     = np.arange(len(scans))
width = 0.35

# ══════════════════════════════════════════════════════════════════════════════
# CHART 1 — Grouped bar: Filtered ports per scan
# Highlights the three spoofing attacks where stateless = 0
# ══════════════════════════════════════════════════════════════════════════════
fig1, ax1 = plt.subplots(figsize=(14, 6))
fig1.patch.set_facecolor(BG)
apply_dark(ax1)

r1 = ax1.bar(x - width/2, sl["Filtered_Ports"], width,
             label="Stateless (Packet Filter)", color=C_SL,
             edgecolor=WHITE, linewidth=0.4, zorder=3)
r2 = ax1.bar(x + width/2, sf["Filtered_Ports"], width,
             label="Stateful (conntrack)",      color=C_SF,
             edgecolor=WHITE, linewidth=0.4, zorder=3)

# Highlight spoofing bypass zones
for i, scan in enumerate(scans):
    if "Spoof" in scan:
        ax1.axvspan(i - width, i + width, alpha=0.10, color=C_OPEN, zorder=1)
        ax1.text(i - width / 2, 0.4, "BYPASSED",
                 ha="center", va="bottom", color=C_OPEN,
                 fontsize=7, fontweight="bold", rotation=90)

autolabel(ax1, r1)
autolabel(ax1, r2)

ax1.set_ylabel("Ports Successfully Filtered / Dropped", fontsize=11)
ax1.set_title(
    "Evasion Resistance by Attack Type  (Higher = Better Protection)\n"
    "Highlighted: Stateless firewall completely bypassed by source-port spoofing",
    fontsize=13, fontweight="bold", pad=16, color=WHITE
)
ax1.set_xticks(x)
ax1.set_xticklabels(scans, rotation=35, ha="right", fontsize=8.5)
ax1.set_ylim(0, 8)
ax1.legend(facecolor=SURFACE, edgecolor=GRID, labelcolor=WHITE, fontsize=10)

fig1.tight_layout()
path1 = os.path.join(CHARTS_DIR, "chart1_evasion_resistance.png")
fig1.savefig(path1, dpi=300, bbox_inches="tight", facecolor=BG)
print(f"[+] Saved {path1}")

# ══════════════════════════════════════════════════════════════════════════════
# CHART 2 — Stacked bar: Port state breakdown (what the attacker actually saw)
# ══════════════════════════════════════════════════════════════════════════════
fig2, (ax2a, ax2b) = plt.subplots(1, 2, figsize=(16, 6), sharey=True)
fig2.patch.set_facecolor(BG)

for ax, fw_df, label in zip([ax2a, ax2b], [sl, sf],
                             ["Stateless Firewall", "Stateful Firewall"]):
    apply_dark(ax)
    xi = np.arange(len(fw_df))

    ax.bar(xi, fw_df["Filtered_Ports"],
           color=C_FILT, edgecolor=BG, linewidth=0.3, label="Filtered", zorder=3)
    ax.bar(xi, fw_df["Closed_Ports"],
           bottom=fw_df["Filtered_Ports"],
           color=C_CLOS, edgecolor=BG, linewidth=0.3, label="Closed", zorder=3)
    ax.bar(xi, fw_df["Open_Ports"],
           bottom=fw_df["Filtered_Ports"] + fw_df["Closed_Ports"],
           color=C_OPEN, edgecolor=BG, linewidth=0.3, label="Open (Bypass!)", zorder=3)

    # Annotate closed (leaked info) and open (service exposed)
    for local_i, row in fw_df.iterrows():
        idx = fw_df.index.get_loc(local_i)
        total = row["Filtered_Ports"] + row["Closed_Ports"] + row["Open_Ports"]
        if row["Closed_Ports"] > 0:
            mid = row["Filtered_Ports"] + row["Closed_Ports"] / 2
            ax.text(idx, mid, f"{int(row['Closed_Ports'])}C",
                    ha="center", va="center", color=WHITE, fontsize=7, fontweight="bold")
        if row["Open_Ports"] > 0:
            ax.text(idx, total + 0.1, f"↑{int(row['Open_Ports'])} open",
                    ha="center", va="bottom", color=C_OPEN, fontsize=7, fontweight="bold")

    ax.set_xticks(xi)
    ax.set_xticklabels(fw_df["Scan_Type"], rotation=35, ha="right", fontsize=8)
    ax.set_title(label, fontsize=13, fontweight="bold", color=WHITE, pad=10)
    ax.set_ylabel("Ports (out of 6 scanned)", fontsize=10)
    ax.set_ylim(0, 9)

p_filt = mpatches.Patch(color=C_FILT, label="Filtered (Blocked — firewall working)")
p_clos = mpatches.Patch(color=C_CLOS, label="Closed (Port replied — info leaked to attacker)")
p_open = mpatches.Patch(color=C_OPEN, label="Open (Service exposed — bypass!)")
fig2.legend(handles=[p_filt, p_clos, p_open], facecolor=SURFACE, edgecolor=GRID,
            labelcolor=WHITE, fontsize=9.5, loc="upper center",
            ncol=3, bbox_to_anchor=(0.5, 1.04))
fig2.suptitle("Port State Breakdown: What the Attacker Actually Received Per Scan",
              fontsize=14, fontweight="bold", color=WHITE, y=1.10)
fig2.tight_layout()
path2 = os.path.join(CHARTS_DIR, "chart2_port_state_breakdown.png")
fig2.savefig(path2, dpi=300, bbox_inches="tight", facecolor=BG)
print(f"[+] Saved {path2}")

# ══════════════════════════════════════════════════════════════════════════════
# CHART 3 — Latency: line + fill
# Key insight: spoof scans are fast on stateless (attacker got responses)
# and slow on stateful (Nmap timeout — attacker got nothing)
# ══════════════════════════════════════════════════════════════════════════════
fig3, ax3 = plt.subplots(figsize=(14, 5))
fig3.patch.set_facecolor(BG)
apply_dark(ax3)

ax3.plot(x, sl["Latency_ms"], color=C_SL, linewidth=2.5,
         marker="o", markersize=7, label="Stateless", zorder=3)
ax3.plot(x, sf["Latency_ms"], color=C_SF, linewidth=2.5,
         marker="s", markersize=7, label="Stateful",  zorder=3)

ax3.fill_between(x, sl["Latency_ms"], sf["Latency_ms"],
                 where=(sf["Latency_ms"] >= sl["Latency_ms"]),
                 alpha=0.15, color=C_SF, label="Stateful overhead / timeout")
ax3.fill_between(x, sl["Latency_ms"], sf["Latency_ms"],
                 where=(sl["Latency_ms"] > sf["Latency_ms"]),
                 alpha=0.10, color=C_SL)

# Annotate the dramatic spoof bypass latency
for i, scan in enumerate(scans):
    if "Spoof" in scan:
        sl_ms = float(sl.loc[sl["Scan_Type"] == scan, "Latency_ms"].values[0])
        sf_ms = float(sf.loc[sf["Scan_Type"] == scan, "Latency_ms"].values[0])
        ax3.annotate(
            f"SL: {int(sl_ms)}ms\n(bypass — got RST)",
            xy=(i, sl_ms), xytext=(i + 0.35, sl_ms + 260),
            arrowprops=dict(arrowstyle="->", color=C_OPEN, lw=1.5),
            color=C_OPEN, fontsize=7.5, fontweight="bold"
        )

ax3.set_xticks(x)
ax3.set_xticklabels(scans, rotation=35, ha="right", fontsize=8.5)
ax3.set_ylabel("Scan Completion Time (ms)", fontsize=11)
ax3.set_title(
    "Scan Latency: Stateless vs. Stateful Firewall\n"
    "Spoof scan latency gap = timeout (stateful) vs. fast RST response (stateless bypass)",
    fontsize=13, fontweight="bold", pad=16, color=WHITE
)
ax3.legend(facecolor=SURFACE, edgecolor=GRID, labelcolor=WHITE, fontsize=10)
ax3.set_ylim(0, max(df["Latency_ms"].max() * 1.35, 500))

fig3.tight_layout()
path3 = os.path.join(CHARTS_DIR, "chart3_latency_comparison.png")
fig3.savefig(path3, dpi=300, bbox_inches="tight", facecolor=BG)
print(f"[+] Saved {path3}")

# ══════════════════════════════════════════════════════════════════════════════
# CHART 4 — Radar: Multi-dimension security posture
# Scores derived from actual experimental filtered port averages
# FIN/NULL/XMAS scored 3/6 (ambiguous open|filtered on both firewalls)
# ══════════════════════════════════════════════════════════════════════════════
def score(fw_df, keys):
    """Average filtered ports for scans whose Scan_Type contains any key."""
    mask = fw_df["Scan_Type"].str.contains("|".join(keys), case=False)
    return fw_df.loc[mask, "Filtered_Ports"].mean() if mask.sum() > 0 else 0

categories = [
    "SYN\nFiltering",
    "Src-Port\nSpoof Block",
    "FIN/NULL/XMAS\nResistance",
    "Fragmentation\nResistance",
    "Decoy Scan\nResistance",
    "ACK Scan\nResistance",
]
N      = len(categories)
angles = np.linspace(0, 2 * np.pi, N, endpoint=False).tolist()
angles += angles[:1]

# Stateless: spoof scores 0 (all bypassed), FIN/NULL/XMAS = 3 (ambiguous)
sl_scores = [
    score(sl, ["Normal_SYN"]),
    score(sl, ["Spoof"]),          # → 0 (bypassed)
    3.0,                           # FIN/NULL/XMAS ambiguous — scored 3/6
    score(sl, ["Fragment"]),
    score(sl, ["Decoy"]),
    score(sl, ["ACK"]),
]
# Stateful: spoof scores 6 (immune), FIN/NULL/XMAS = 3 (same ambiguity)
sf_scores = [
    score(sf, ["Normal_SYN"]),
    score(sf, ["Spoof"]),          # → 6 (immune)
    3.0,                           # FIN/NULL/XMAS ambiguous — scored 3/6
    score(sf, ["Fragment"]),
    score(sf, ["Decoy"]),
    score(sf, ["ACK"]),
]

sl_scores_c = sl_scores + sl_scores[:1]
sf_scores_c = sf_scores + sf_scores[:1]

fig4, ax4 = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))
fig4.patch.set_facecolor(BG)
ax4.set_facecolor(SURFACE)
ax4.spines["polar"].set_color(GRID)
ax4.tick_params(colors=WHITE, labelsize=9)

ax4.plot(angles, sl_scores_c, color=C_SL, linewidth=2.5, label="Stateless")
ax4.fill(angles, sl_scores_c, color=C_SL, alpha=0.20)
ax4.plot(angles, sf_scores_c, color=C_SF, linewidth=2.5, label="Stateful")
ax4.fill(angles, sf_scores_c, color=C_SF, alpha=0.25)

# Annotate the critical gap
spoof_angle = angles[1]
ax4.annotate(
    "CRITICAL GAP\n(total bypass)",
    xy=(spoof_angle, 0.5),
    color=C_OPEN, fontsize=8.5, fontweight="bold", ha="center"
)

ax4.set_ylim(0, 6)
ax4.set_yticks([1, 2, 3, 4, 5, 6])
ax4.set_yticklabels(["1", "2", "3", "4", "5", "6"], color=MUTED, fontsize=8)
ax4.set_xticks(angles[:-1])
ax4.set_xticklabels(categories, color=WHITE, fontsize=9)
ax4.yaxis.grid(True, color=GRID, linestyle="--", alpha=0.6)
ax4.xaxis.grid(True, color=GRID, linestyle="--", alpha=0.4)
ax4.set_title(
    "Security Posture Comparison\n(Derived from Actual Lab Results — max score 6)",
    fontsize=12, fontweight="bold", color=WHITE, pad=24
)
ax4.legend(facecolor=SURFACE, edgecolor=GRID, labelcolor=WHITE,
           fontsize=11, loc="upper right", bbox_to_anchor=(1.35, 1.12))

fig4.tight_layout()
path4 = os.path.join(CHARTS_DIR, "chart4_radar_posture.png")
fig4.savefig(path4, dpi=300, bbox_inches="tight", facecolor=BG)
print(f"[+] Saved {path4}")

# ── Summary ───────────────────────────────────────────────────────────────────
print()
print("══════════════════════════════════════════════")
print(" RESULT SUMMARY")
print("══════════════════════════════════════════════")
excl = df[~df["Scan_Type"].isin(["FIN_Scan", "NULL_Scan", "XMAS_Scan"])]
sl_e = excl[excl.Firewall == "Stateless"]
sf_e = excl[excl.Firewall == "Stateful"]
total_p = len(sl_e) * 6
sl_f = int(sl_e["Filtered_Ports"].sum())
sf_f = int(sf_e["Filtered_Ports"].sum())
print(f"Port probes per firewall (excl. ambiguous class) : {total_p}")
print(f"Stateless — total filtered : {sl_f}/{total_p} ({100*sl_f/total_p:.1f}%)")
print(f"Stateful  — total filtered : {sf_f}/{total_p} ({100*sf_f/total_p:.1f}%)")
if "Latency_ms" in df.columns:
    sl_avg = sl["Latency_ms"].mean()
    sf_avg = sf["Latency_ms"].mean()
    print(f"Stateless avg latency      : {sl_avg:.0f} ms")
    print(f"Stateful  avg latency      : {sf_avg:.0f} ms")
    oh = (sf_avg - sl_avg) / sl_avg * 100
    print(f"Overall latency overhead   : {oh:+.1f}%")
print("══════════════════════════════════════════════")
print("[+] All 4 charts saved to charts/")
print("    Embed them into your Word document.")
